[advisories]
unmaintained = "transitive"
yanked = "warn"

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-3.0",
    "MPL-2.0",
]

[[licenses.clarify]]
name = "owlzops-mapper"
license-files = [{ path = "LICENSE", hash = "73d920e2ceebdc325b90a73d6ca9ffe171bf35c4e5f32980bbeb76b4fa6f471" }]
expression = "Apache-2.0"

[bans]
multiple-versions = "warn"